Add schedule feature and schedule command
AY2324S1-CS2103-F13-1/tp pull request #159
Opened 2023-10-26 10:20 UTC by geoffong11

Format: schedule INDEX i/YYYY-MM-DD-HH-MM [a/SCHEDULENAME].

First, the `ScheduleCommandParser` object parses the command and creates a `ScheduleDescriptor` object (under ScheduleCommand as a static class) using Schedule, ScheduleName, and LastModifiedTime objects. Suppose ScheduleName is not specified, the meeting will be called `Meeting` Then it creates a ScheduleCommand that takes in the Index of Person to change and the ScheduleDescriptor. Through ScheduleCommand#execute(), replaces the original Person object (by Index), after editing the Schedule, ScheduleName, and LastModifiedDateTime object in the Person through a secondary constructor, that takes in Optional<Schedule> and Optional<ScheduleName>. Confirmation string is then printed.

`Optional` wrapper is used for Schedule and ScheduleName objects in Person object since upon initialization, they technically do not have a Schedule. I don't know if that is the best way forward, but I guess for ClearSchedule, it will be easier to implement (put in Optional.empty() as the variables).

2023-10-26 14:45 UTC, imkwokyong reviewed
After tinkering with the code, I found some bugs:
1. Invalid datetime like `2020-00-01-01-30` and `2020-01-31-25-30` throws exceptions that are not handled implicitly
2. For the February month, is there a reason why `2021-02-31...` defaults to `2021 Feb 28 ...` in the personListPanel instead of saying invalid date time to the user?

![image](https://github.com/AY2324S1-CS2103-F13-1/tp/assets/110521168/2ec40742-38fd-4aaa-9e90-b90c5c64a586)


Suggestions:
1. Check whether provided datetime is later than current datetime; if no, throw error message saying something like, "The provided datetime is over long ago' or something like that.

2023-10-26 14:49 UTC, xavierpok commented
Closes #166

2023-10-26 15:00 UTC, xavierpok commented on src/main/java/connexion/logic/commands/ScheduleCommand.java
> +    public static class ScheduleDescriptor {
Not a suggestion, but next time we talk about this, we can table somehow unifying the (with my PR) 3 classes that use some kind of static nested `Descriptor` under an interface. Not a pressing issue, though.

2023-10-26 15:02 UTC, xavierpok commented on src/main/java/connexion/model/person/Schedule.java
> +            DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm");
Will probably throw some kind of `[DateTimeParseException](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeParseException.html)`

2023-10-27 06:10 UTC, xavierpok commented on src/main/java/connexion/model/person/Schedule.java
> +            DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm");
implemented

2023-10-27 06:13 UTC, xavierpok commented
> 1. Invalid datetime like `2020-00-01-01-30` and `2020-01-31-25-30` throws exceptions that are not handled implicitly
Now throws a ParseException but still needs a test case added for this 
Checked by `isValid` now 
> 2. For the February month, is there a reason why `2021-02-31...` defaults to `2021 Feb 28 ...` in the personListPanel instead of saying invalid date time to the user?
Handled by changing of `ResolverStyle `to STRICT

>3. Check whether provided ......

Will open issue collating suggested feature expansions after schedule PR merged

2023-10-27 08:56 UTC, xavierpok requested changes

2023-10-27 08:56 UTC, xavierpok commented on src/main/java/connexion/logic/commands/ScheduleCommand.java
> +    }
```suggestion
        Person toReturn =  new Person(name, phone, email, company, job, tags,
                updatedSchedule, updatedScheduleName, updatedLastModifiedDateTime);
        if (personToEditSchedule.getValue()) { // if the person was marked
            toReturn.mark();
        } else { // if the person was unmarked
            toReturn.unmark();
        }
        return toReturn;
    }
```

2023-10-27 08:56 UTC, xavierpok commented on src/main/java/connexion/logic/commands/ScheduleCommand.java
> +    }
Should add mark copying. Above code block should resolve.

2023-10-27 08:56 UTC, xavierpok commented on src/main/java/connexion/logic/commands/ScheduleCommand.java
> +    }
Tests currently (probably) don't check for mark copying. Should add as a test case also.

2023-10-29 03:39 UTC, xavierpok reviewed
All outstanding issues raised in an earlier comment look resolved, LGTM, but merge conflicts with PR #172 need to be resolved. Suggest waiting for resolution before merging.

2023-10-29 09:25 UTC, xavierpok approved these changes
Forgot to approve, LGTM

2023-10-29 18:25 UTC, imkwokyong approved these changes
LGTM! Thanks for fixing the aforementioned bugs and the merge conflicts!

2023-10-29 18:25 UTC, merged