Update schedule UG description, edit jsonAdaptedPerson to get intended behaviour for json file.
AY2324S1-CS2103-F13-1/tp pull request #238
Opened 2023-11-07 05:29 UTC by geoffong11

Add checking of `schedule` and `ScheduleName` to make sure they both exist or both do not. Update the `schedule` feature in UserGuide. Also trimmed all fields in jsonAdaptedPerson so that if someone edits the json file by adding whitespaces, it will still load the json file.

2023-11-07 05:31 UTC, geoffong11 commented
Closes #228

2023-11-07 05:32 UTC, geoffong11 commented
Closes #201 
Edit Phone number and relevant tests so that phone number length can only be 3 to 15 numbers long

2023-11-08 15:44 UTC, xavierpok requested changes
LGTM for the most part, but I'm not too sure about the change to disallow the combo of no name + schedule time in the JSON file

2023-11-08 15:44 UTC, xavierpok commented on src/main/java/connexion/storage/JsonAdaptedPerson.java
>          }
I might be missing something, but won't this disallow the combination of no name but present schedule?

Is this intended behaviour, or is the intended behaviour only for no schedule name to be allowed only in the UI?

If it's intended behaviour, might need a clause in the updated UG to reflect that the combo of no name + schedule is valid only for UI entry and NOT for manual JSON editing

2023-11-08 15:44 UTC, xavierpok commented on src/test/java/connexion/storage/JsonAdaptedPersonTest.java
> +
A bit of a nit, but it might be better to add a test case testing the new whitespace stripping behaviour

Because that's arguably a new behaviour (in that there's some post-processing going on on the JSON input)

2023-11-08 15:44 UTC, xavierpok commented on docs/UserGuide.md
>  *  `schedule 3 i/2024-05-06-18-00 a/Evening seminar` edits or adds the 3rd person's schedule time and name, where the schedule time is `6 May 2024, 18:00:00`, and the schedule name is `Evening semina
Another small documentation issue, we might need to specify the new behaviour of whitespace-stripping in the UG because it's not explicitly stated and hence ambiguous. The UI strips but to be safe maybe it will be best if we specify in the UG also?

I think it's ambiguous enough to go either way, so see what you think!

2023-11-08 15:45 UTC, xavierpok commented
> LGTM for the most part, but I'm not too sure about the change to disallow the combo of no name + schedule time in the JSON file

Overall, thanks for helping catch this issue that we missed!

2023-11-08 15:45 UTC, xavierpok commented on docs/UserGuide.md
>  *  `schedule 3 i/2024-05-06-18-00 a/Evening seminar` edits or adds the 3rd person's schedule time and name, where the schedule time is `6 May 2024, 18:00:00`, and the schedule name is `Evening semina
Non-critical, is ok to merge w/o addressing this

2023-11-10 05:55 UTC, geoffong11 commented
Feature flaw, not bug.

2023-11-10 05:55 UTC, closed without merging