Clarifies restrictions on fields
AY2324S1-CS2103-F13-1/tp pull request #246
Opened 2023-11-08 06:29 UTC by xavierpok

Closes issue #194  by clarifying it's intended behaviour

Also improves upon the UG by listing out restrictions for our fields.

(Email parsing is surprisingly complex so the section is a killer)

2023-11-08 21:07 UTC, imkwokyong requested changes
Just some nits and need to resolve merge conflicts. Thank you for helping to update the documentation!

2023-11-08 21:07 UTC, imkwokyong commented on docs/UserGuide.md
> +| o/     | NOTE          | Alphanumeric characters, punctuation(any of ``!"#$%&'()*+,-./:;<=>?@[\]^`{\| }~``)  and whitespace. Maximum of 1000 characters.
Can add here that it could be empty

2023-11-08 21:07 UTC, imkwokyong commented on docs/UserGuide.md
> +| o/     | NOTE          | Alphanumeric characters, punctuation(any of ``!"#$%&'()*+,-./:;<=>?@[\]^`{\| }~``)  and whitespace. Maximum of 1000 characters.
Punctuation-wise no problem, checked in app and every punctuation here is accepted.

2023-11-08 21:07 UTC, imkwokyong commented on docs/UserGuide.md
> +| p/     | PHONE_NUMBER  | 3-15 numeric characters.
Suggest to add non-empty here too

2023-11-09 05:52 UTC, xavierpok commented
Merge conflicts resolved & changes implemented.

Of note :

`note` in fact allows empty fields
Added note that whitespaces are stripped.

2023-11-09 06:14 UTC, imkwokyong approved these changes
LGTM!

2023-11-09 06:14 UTC, merged