Fix email parsing
AY2324S1-CS2103-F13-1/tp pull request #247
Opened 2023-11-08 07:55 UTC by xavierpok

Closes #202 

The regex is still mostly impenetrable without taking a moment to figure out what it actually means but should be a bit better

Regex in this PR will become 
`^ALPHANUMERIC((SPECIAL_CHAR|ALPHANUMERIC)*ALPHANUMERIC)?`

Which roughly means that it must start with an alphanumeric (w/o underscore) character, then (optional) have zero or more of either (special char or alphanumeric) followed by one alphanumeric.

This should be right, though I invite anyone who's reviewing to double-check that this makes sense.

Test cases updated to reflect this new behaviour. There was a test case for this exact scenario that was supposed to fail, in contrast to advertised behaviour.

2023-11-08 08:01 UTC, xavierpok commented
Converted to draft to address #204

2023-11-09 15:13 UTC, imkwokyong requested changes
A nit about the error message

2023-11-09 15:13 UTC, imkwokyong commented on src/main/java/connexion/model/person/Email.java
>              + "1. The local-part should only contain alphanumeric characters and these special characters, excluding "
![image](https://github.com/AY2324S1-CS2103-F13-1/tp/assets/110521168/7ab5735f-ae7c-4487-99f7-6bc593546cae)
might need to fix the ([+_.-]+) part cause it's in regex form and might confuse the users with the square brackets and the "+" sign behind

2023-11-09 15:18 UTC, xavierpok commented on src/main/java/connexion/model/person/Email.java
>              + "1. The local-part should only contain alphanumeric characters and these special characters, excluding "
Done!

2023-11-09 15:22 UTC, imkwokyong approved these changes
LGTM!

2023-11-09 15:22 UTC, merged